INSERT INTO categories (name, image, description)
VALUES
    ('Electronics', 'electronics.jpg', 'Devices and gadgets for daily use'),
    ('Books', 'books.jpg', 'A variety of books across genres'),
    ('Clothing', 'clothing.jpg', 'Apparel for all seasons and styles');

-- Insert brands
INSERT INTO brands (name, image, description)
VALUES
    ('Brand A', 'brand_a.jpg', 'Quality and reliable products'),
    ('Brand B', 'brand_b.jpg', 'Innovative and modern design'),
    ('Brand C', 'brand_c.jpg', 'Affordable and durable items');


INSERT INTO products (name, description, price, stock, totalViews, isFeatured, status, averageRating, slug, categoryId, brandId)
VALUES
-- Start of generated products
('Product 1', 'Description for Product 1', 20.50, 100, 10, 0, 1, 4.5, 'product-1', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 2', 'Description for Product 2', 15.99, 50, 5, 1, 1, 4.0, 'product-2', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 3', 'Description for Product 3', 30.00, 200, 15, 0, 1, 3.8, 'product-3', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 4', 'Description for Product 4', 45.75, 120, 25, 1, 1, 4.7, 'product-4', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 5', 'Description for Product 5', 10.00, 80, 2, 0, 1, 3.5, 'product-5', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
-- Repeat similar pattern for 95 more products
('Product 6', 'Description for Product 6', 22.99, 60, 8, 0, 1, 4.2, 'product-6', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 7', 'Description for Product 7', 99.99, 30, 50, 1, 1, 4.9, 'product-7', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 8', 'Description for Product 8', 7.50, 150, 12, 0, 1, 3.6, 'product-8', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 9', 'Description for Product 9', 25.00, 20, 18, 1, 1, 4.3, 'product-9', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 10', 'Description for Product 10', 13.49, 70, 6, 0, 1, 3.9, 'product-10', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 11', 'Description for Product 11', 19.99, 120, 14, 1, 1, 4.1, 'product-11', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 12', 'Description for Product 12', 35.49, 90, 22, 0, 1, 4.4, 'product-12', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 13', 'Description for Product 13', 50.00, 40, 60, 1, 1, 4.8, 'product-13', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 14', 'Description for Product 14', 12.49, 200, 10, 0, 1, 3.7, 'product-14', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 15', 'Description for Product 15', 27.50, 85, 18, 1, 1, 4.0, 'product-15', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 16', 'Description for Product 16', 9.99, 130, 5, 0, 1, 3.3, 'product-16', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 17', 'Description for Product 17', 39.95, 75, 30, 1, 1, 4.6, 'product-17', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 18', 'Description for Product 18', 8.75, 60, 7, 0, 1, 3.4, 'product-18', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 19', 'Description for Product 19', 23.49, 90, 12, 1, 1, 3.9, 'product-19', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3))),
('Product 20', 'Description for Product 20', 45.00, 50, 40, 1, 1, 4.7, 'product-20', FLOOR(1 + (RAND() * 3)), FLOOR(1 + (RAND() * 3)));




INSERT INTO product_images ( image, isMain, productId) VALUES
                                                           ( 'image_1_1.jpg', 1, 1),
                                                           ( 'image_2_1.jpg', 1, 2),
                                                           ( 'image_2_2.jpg', 0, 2),
                                                           ( 'image_2_3.jpg', 0, 2),
                                                           ( 'image_2_4.jpg', 0, 2),
                                                           ( 'image_2_5.jpg', 0, 2),
                                                           ( 'image_3_1.jpg', 1, 3),
                                                           ( 'image_3_2.jpg', 0, 3),
                                                           ( 'image_3_3.jpg', 0, 3),
                                                           ( 'image_3_4.jpg', 0, 3),
                                                           ( 'image_3_5.jpg', 0, 3),
                                                           ( 'image_4_1.jpg', 1, 4),
                                                           ( 'image_4_2.jpg', 0, 4),
                                                           ( 'image_4_3.jpg', 0, 4),
                                                           ( 'image_5_1.jpg', 1, 5),
                                                           ( 'image_5_2.jpg', 0, 5),
                                                           ( 'image_5_3.jpg', 0, 5),
                                                           ( 'image_6_1.jpg', 1, 6),
                                                           ( 'image_6_2.jpg', 0, 6),
                                                           ( 'image_6_3.jpg', 0, 6),
                                                           ( 'image_6_4.jpg', 0, 6),
                                                           ( 'image_6_5.jpg', 0, 6),
                                                           ( 'image_7_1.jpg', 1, 7),
                                                           ( 'image_7_2.jpg', 0, 7),
                                                           ( 'image_7_3.jpg', 0, 7),
                                                           ( 'image_8_1.jpg', 1, 8),
                                                           ( 'image_8_2.jpg', 0, 8),
                                                           ( 'image_8_3.jpg', 0, 8),
                                                           ( 'image_8_4.jpg', 0, 8),
                                                           ( 'image_9_1.jpg', 1, 9),
                                                           ( 'image_10_1.jpg', 1, 10),
                                                           ( 'image_10_2.jpg', 0, 10),
                                                           ( 'image_11_1.jpg', 1, 11),
                                                           ( 'image_11_2.jpg', 0, 11),
                                                           ( 'image_11_3.jpg', 0, 11),
                                                           ( 'image_11_4.jpg', 0, 11),
                                                           ( 'image_11_5.jpg', 0, 11),
                                                           ( 'image_12_1.jpg', 1, 12),
                                                           ( 'image_12_2.jpg', 0, 12),
                                                           ( 'image_13_1.jpg', 1, 13),
                                                           ( 'image_13_2.jpg', 0, 13),
                                                           ( 'image_14_1.jpg', 1, 14),
                                                           ( 'image_15_1.jpg', 1, 15),
                                                           ( 'image_15_2.jpg', 0, 15),
                                                           ( 'image_16_1.jpg', 1, 16),
                                                           ( 'image_16_2.jpg', 0, 16),
                                                           ( 'image_16_3.jpg', 0, 16),
                                                           ( 'image_16_4.jpg', 0, 16),
                                                           ( 'image_17_1.jpg', 1, 17),
                                                           ( 'image_17_2.jpg', 0, 17),
                                                           ( 'image_17_3.jpg', 0, 17),
                                                           ( 'image_17_4.jpg', 0, 17),
                                                           ( 'image_17_5.jpg', 0, 17),
                                                           ( 'image_18_1.jpg', 1, 18),
                                                           ( 'image_18_2.jpg', 0, 18),
                                                           ( 'image_19_1.jpg', 1, 19),
                                                           ( 'image_19_2.jpg', 0, 19),
                                                           ( 'image_19_3.jpg', 0, 19),
                                                           ( 'image_19_4.jpg', 0, 19),
                                                           ( 'image_19_5.jpg', 0, 19),
                                                           ( 'image_20_1.jpg', 1, 20),
                                                           ( 'image_20_2.jpg', 0, 20);

-- Insert data into product_colors
INSERT INTO product_colors (colorCode, colorName, productId) VALUES
                                                                 ( '#FFFFFF', 'White', 1),
                                                                 ( '#000000', 'Black', 1),
                                                                 ( '#3357FF', 'Blue', 1),
                                                                 ( '#FF33FF', 'Magenta', 1),
                                                                 ( '#33FF57', 'Green', 2),
                                                                 ( '#FF33FF', 'Magenta', 2),
                                                                 ( '#33FF57', 'Green', 3),
                                                                 ( '#FF33FF', 'Magenta', 3),
                                                                 ( '#FF5733', 'Red', 3),
                                                                 ( '#33FFFF', 'Cyan', 3),
                                                                 ( '#FFFF33', 'Yellow', 3),
                                                                 ( '#000000', 'Black', 4),
                                                                 ( '#FFFFFF', 'White', 5),
                                                                 ( '#FFFF33', 'Yellow', 5),
                                                                 ( '#3357FF', 'Blue', 5),
                                                                 ( '#33FF57', 'Green', 5),
                                                                 ( '#FFFFFF', 'White', 6),
                                                                 ( '#000000', 'Black', 6),
                                                                 ( '#FF33FF', 'Magenta', 6),
                                                                 ( '#FF5733', 'Red', 7),
                                                                 ( '#FFFFFF', 'White', 7),
                                                                 ( '#000000', 'Black', 8),
                                                                 ( '#3357FF', 'Blue', 8),
                                                                 ( '#FFFF33', 'Yellow', 9),
                                                                 ( '#3357FF', 'Blue', 10),
                                                                 ( '#FFFF33', 'Yellow', 10),
                                                                 ( '#FFFFFF', 'White', 10),
                                                                 ( '#33FF57', 'Green', 10),
                                                                 ( '#FF5733', 'Red', 10),
                                                                 ( '#FFFF33', 'Yellow', 11),
                                                                 ( '#000000', 'Black', 11),
                                                                 ( '#FF33FF', 'Magenta', 11),
                                                                 ( '#FFFF33', 'Yellow', 12),
                                                                 ( '#33FFFF', 'Cyan', 12),
                                                                 ( '#33FF57', 'Green', 12),
                                                                 ( '#FF5733', 'Red', 12),
                                                                 ( '#3357FF', 'Blue', 12),
                                                                 ( '#FFFFFF', 'White', 13),
                                                                 ( '#000000', 'Black', 13),
                                                                 ( '#33FF57', 'Green', 13),
                                                                 ( '#33FF57', 'Green', 14),
                                                                 ( '#FF5733', 'Red', 14),
                                                                 ( '#FFFFFF', 'White', 14),
                                                                 ( '#000000', 'Black', 14),
                                                                 ( '#33FFFF', 'Cyan', 14),
                                                                 ( '#FF5733', 'Red', 15),
                                                                 ( '#33FF57', 'Green', 15),
                                                                 ( '#FFFF33', 'Yellow', 15),
                                                                 ( '#33FF57', 'Green', 16),
                                                                 ( '#FF33FF', 'Magenta', 16),
                                                                 ( '#33FFFF', 'Cyan', 16),
                                                                 ( '#FF5733', 'Red', 16),
                                                                 ( '#FFFFFF', 'White', 16),
                                                                 ( '#FFFFFF', 'White', 17),
                                                                 ( '#33FFFF', 'Cyan', 17),
                                                                 ( '#33FF57', 'Green', 18),
                                                                 ( '#3357FF', 'Blue', 18),
                                                                 ( '#33FFFF', 'Cyan', 18),
                                                                 ( '#3357FF', 'Blue', 19),
                                                                 ( '#FFFF33', 'Yellow', 20);



